"""Initial Migration

Revision ID: f96e259970f8
Revises: c2c2c278d172
Create Date: 2019-05-27 14:29:16.187874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96e259970f8'
down_revision = 'c2c2c278d172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('vote_count', sa.Integer(), nullable=True))
    op.drop_column('reviews', 'pitch_title')
    op.drop_column('reviews', 'pitch_review_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('pitch_review_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('pitch_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'vote_count')
    op.drop_column('pitches', 'likes')
    op.drop_column('pitches', 'dislikes')
    # ### end Alembic commands ###
